### ISSUE TITLE
[Chapter] payment batching

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/scaling-book#10]
Based on https://bitcointechtalk.com/saving-up-to-80-on-bitcoin-transaction-fees-by-batching-payments-4147ab7009fb

**Comment by harding** [comment]
I'll take this.  Proposed outline (suggestions welcome):

- What is it / the basic idea / who will benefit the most from implementing it
- Amount of savings available
- Concerns: UX, privacy, max default tx size for relay, sudden fee increases causing stuck payments, problems with CPFP on large txes
- Implementation (using an existing wallet, namely Bitcoin Core; or constructing your own transactions)
- Serendipitous combinations: with good coin selection for changless transactions; with RBF for fast relay but still low(ish) fees

Self-imposed due date for opening PR: 2019-02-07

**Comment by moneyball** [comment]
For the privacy concern, which I have heard from some companies, I think it is important to speak to the marginal privacy leak, if any, versus the absolute. ie Large exchanges are likely to have already been identified through chain analysis so does payment batching actually leak more privacy details?

**Comment by harding** [comment]
@moneyball good point!  I will try to work that in.  That said, I do think it's important to mention the concern because there's no fundamental reason exchanges can't provide good resistance against chain analysis.  Part of the reason they fail at it is because they often don't implement other best-practice recommendations, such as avoiding address reuse.

![2019-01-25-12_56_11_338927929](https://user-images.githubusercontent.com/61096/51764092-335c7980-20a2-11e9-968d-88b323025110.png)
