### ISSUE TITLE
Add diagrams

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/scaling-book#6]
All sections will require diagrams. For starters, CPFP and RBF.

**Comment by marcopesani** [comment]
I started to work on one of the most complex topics to visualize, RBF. What I'm showing you is NOT a graphic proposal, it is more like a wireframe to start the discussion.

Here some key points:
- Many of the diagrams are, in reality, flows. These flows requires some context to be properly understood. An example, the first step of the RBF flow, probably can be part of a previous chapter about the fee market.
- My objective is not to rely on supporting text or, at least, to have not the text included in the image. It will require some iterations and feedbacks.
- I'd love to keep the graphic design minimal, without colors and complex shapes. Objective n.1 is clarity, n.2 accessibility (visually impaired, color blinds people...), n.3 is "fanciness"

![rbf](https://user-images.githubusercontent.com/50498/54301101-948ecc80-45be-11e9-9fe8-f91c0eecc2e2.jpg)

Let me know what do you think of this approach. In the next few days, I'll work on charts (I'll open a dedicated issue) and graphic style proposal.

**Comment by harding** [comment]
@marcopesani nice!  Some comments:

1. I know you're trying to remove text, but insofar as some might need to be included, I'd prefer to use "feerate" instead of "fee".  I think most people associate fee with the absolute amount of fee a transaction pays (e.g. 123 uBTC) but what matters is the amount of fee per size (as your sample correctly illustrates), which the term "feerate" captures

2. Steps three and four aren't quite correct.  When Alice's node receives a potential replacement, it checks to see whether it satisfies all the RBF criteria (including paying a higher feerate).  If it does, the previous version is removed from the mempool and the new version added simultaneously.  In common speech, the new version *replaces* the old version.  This happens irrespective of block production.  In Bitcoin Core terminology, two transactions that contain any of the same inputs are *conflicting* transactions (because they can't both be part of the same valid block chain) and Bitcoin Core's mempool should never contain any conflicts.

3. I think the introduction of the 3500 sat/vbyte transaction in step three confuses things (although it is  realistic about mempool contents changing over time).

4. I understand that this is just a draft, so maybe this is just a fine-details thing, but the replacement in step three should have a difference in its input or output values (or both) to correspond to the feerate change.  E.g. if the original transacation `tx` has an input of 100 and an output of 90, then 10 is allocated to fee.  To double its fee (and feerate), the replacement `tx'` would probably keep the input the same at 100 and reduce the output to 80, allocating 20 to fee.

5. We need to figure out some guidelines for maximum image width (height is less important IMO).  If this is going to be an actual book, some people are probably going to be reading this in profile view on their phone.  That's obviously not going to work with wide flows:

    ![2019-03-13-18_54_23_117985373](https://user-images.githubusercontent.com/61096/54319883-82faf400-45c1-11e9-9487-7368ae6efe18.png)

6. Before any significant work is done on hard-to-change illustrations, we probably need to figure out what units we're going to use.  Sat/vbyte is the most common expression of free rate out now probably due to Bitcoin Core's default minimum being 1,000 sat/1,000 vbytes (= 1 sat/vB).  However, there's nothing inherently preventing fractional sats from being used as feerates (and I even have my node configured to accept 0.1 sat/vB txes), at which point I would argue (with personal bias) that we ought as well use nBTC.  :-)

7. Finally, will the image source files be made available in a format that can be opened by a free software (open source) program in case any of us wants to modify them ourselves in the future?  E.g. Inkscape or Gimp?

**Comment by marcopesani** [comment]
Ok, here a second iteration based on received feedbacks.
1. Simplified a lot the representation to focus on the most important message: "You can replace a transaction".
2. I'm quite agnostic about the units. I think that the curators of the book should define a standard and I'll follow it :)
3. About the software, I'd prefer to rely on a web standard SVG rather than a specific format. I think that anyone should be free to use the preferred visual editor. Also, I'd love to work on the SVG accessibility, in order to guarantee to visually impaired people to benefit from the informations contained inside the illustrations.

<img src="https://user-images.githubusercontent.com/50498/54562319-14ee6c80-49c7-11e9-8381-6c2f1826698a.png" width="450">

Here the SVG gist (quick export, not optimized at all)
[https://gist.github.com/marcopesani/8d7f0c79b59df5a5ed3964917bac247b#file-rbf-svg](https://gist.github.com/marcopesani/8d7f0c79b59df5a5ed3964917bac247b#file-rbf-svg)

**Comment by harding** [comment]
@marcopesani Thanks!  A few more notes:

1. The transaction ID (txid) of the replacement will be different than the original because the txid is formed by hashing all of the data in the transaction (exclusive of the witness stuff in segwit txes).  This includes the output amounts, so when the replacement claims less output, the replacement gets a totally different txid.

    The way software tracks replacements is by tracking the inputs.  Each input contains an identifier called an "outpoint" that points to the output being spent.  The output uses the txid of that output being spent and the location (index number) of the output within the block, with outputs numbered sequentially from zero.  Devs sometimes express that as `<txid>:<index>` or something like `1234...cdef:987`.  So if `tx` spends input abcd:0 and `tx'` spends that same input, `tx'` is a potential replacement of `tx`.

2. SVG is great!

3. I'd prefer figures not include numbers in the illustration as that would require editing each figure any time we insert a new image earlier in a chapter (although, admittedly, with SVG, that could probably be automated without much difficulty).

Besides those two nitpicks, I think this particular illustration is looking good and that we're in agreement on the basic principles that can help speed future work.  Thanks again!
