### ISSUE TITLE
[Chapter] pubkey and signature encoding

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/scaling-book#9]
It'd be useful to have a chapter that discusses the changes in pubkey and signature encoding. I think they belong in the same chapter because they're both the same concept: trimming the fat so the minimal required data is stored on the blockchain/UTXO set.

- pubkeys were originally uncompressed, changed to compressed in v0.6: https://bitcoin.org/en/release/v0.6.0 [65 -> 33 bytes per pubkey]
- signature encoding:
    - Originally, Bitcoin accepted any ASN.1 BER encoded signature. The maximum length for those signatures was platform-dependent (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-July/009697.html)
    - BIP 66 caused Bitcoin to enforce strict DER signatures, which limited the signature size to a maximum of 73 bytes (https://github.com/bitcoin/bips/blob/master/bip-0066.mediawiki)
    - Bitcoin Core has produced 'low S' signatures since https://github.com/bitcoin/bitcoin/pull/3016, reducing maximum signature size to 72 bytes (7 bytes overhead, 32 bytes for S, 33 bytes for R). High S signatures were made non-standard in https://github.com/bitcoin/bitcoin/pull/6769.
    - Bitcoin Core has produced 'low R' signatures since https://github.com/bitcoin/bitcoin/pull/13666, reducing maximum signature size to 71 bytes (7 bytes overhead, 32 bytes for S, 33 bytes for R).
    - the Schnorr signature proposal at https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki encodes the R point and s value without DER padding, fixing all signatures size to 64 bytes.

Good references for DER encoding:
- https://bitcoin.stackexchange.com/a/77192/26940
- code comment at https://github.com/bitcoin/bips/blob/master/bip-0066.mediawiki#der-encoding-reference

**Comment by SomberNight** [comment]
> Bitcoin Core has produced 'low R' signatures since bitcoin/bitcoin#13666, reducing maximum signature size to 71 bytes (7 bytes overhead, 32 bytes for S, 33 bytes for R).

typo: 32 bytes for R

> the Schnorr signature proposal at https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki encodes the R point and s value without DER padding, fixing all signatures size to 64 bytes.

In the above bullet points, 1 byte of that "7 byte overhead" was the sighash byte.
With Schnorr sigs, [according to bip-taproot](https://github.com/sipa/bips/blob/4c638b38435d48797016a8eb08aae38ce3b1eaf3/bip-taproot.mediawiki#signature-validation-rules), the signature is only 64 bytes iff it is using SIGHASH_ALL.

**Comment by 0xB10C** [comment]
I spoke about this chapter with @bitschmidty roughly a month ago. I'm not sure if there has been progress since then. I dove a bit into it myself and wanted to share that with you. Please let me know if I can help by e.g. contributing data, code or more. Thank you @jnewbery for the helpful bullet points and links!

---

![LengthOfECDSASig](https://user-images.githubusercontent.com/19157360/76680383-60daee00-65e8-11ea-8e6c-1fad9958d20c.png)
![lengthofecdsa-legend](https://user-images.githubusercontent.com/19157360/76680566-deebc480-65e9-11ea-8867-af44adac94bb.png)

I have a section on why there are different length ECDSA signatures and how any why the length distribution evolved over time on the [Length of ECDSA Signatures](https://transactionfee.info/charts/bitcoin-script-ecdsa-length/) page.

Additionally, the evolution of low and high `r` and `S` values (high values need padding -> make signatures longer) can be seen on [r and S-values in Bitcoin ECDSA Signatures](https://transactionfee.info/charts/bitcoin-script-ecdsa-rs-values/).

![r-S-values](https://user-images.githubusercontent.com/19157360/76680794-165b7080-65ec-11ea-9f5b-6308dfc9c805.png)
![r-s-values-legend](https://user-images.githubusercontent.com/19157360/76680795-18253400-65ec-11ea-82ca-eb3cd859fb4a.png)

Separately covered on the [r-values in ECDSA Signatures](https://transactionfee.info/charts/bitcoin-script-ecdsa-r-value/) and the [S-values in ECDSA Signatures](https://transactionfee.info/charts/bitcoin-script-ecdsa-s-value/) pages.

---

![ecdsa-der-not-der](https://user-images.githubusercontent.com/19157360/76680607-2eca8b80-65ea-11ea-940f-d60b780b42d7.png)

(Blue is _valid under DER_, Yellow is _not valid under DER_) 

Most signatures are valid under the DER rule-set. There were a few signatures between 2011 and 2013 which are not valid DER. Interactive version of [DER encoded ECDSA Signatures](https://transactionfee.info/charts/bitcoin-script-ecdsa-strict-der/).

--- 

![pubkeys](https://user-images.githubusercontent.com/19157360/76681459-2f1b5480-65f3-11ea-8716-3d7b9c8e7957.png)

(Blue is _uncompressed_, yellow is _compressed_)

[Interactive version](https://transactionfee.info/charts/bitcoin-script-pubkey-compression/)

**Comment by bitschmidty** [comment]
@0xB10C This is really great and these charts will come in handy. Right now in my drafts I have placeholder text for such charts.

Thanks so much for putting these together! I might reach out on a couple more charts I had in mind if that’s ok?

**Comment by 0xB10C** [comment]
Sure, please don't hesitate to reach out. I'd be happy to provide raw data so you don't have to copy these screenshots.

**Comment by jnewbery** [comment]
Wow. I love these charts. Thanks @0xB10C !

**Comment by harding** [comment]
@0xB10C these charts are amazing, thank you!  For "Compression of spend PubKeys", it isn't clear to me whether the chart represents the ratio of transactions, inputs, or pubkeys.  Additionally, how are you counting bare multisig and P2PK; is the type of the pubkey counted when the UTXO is created (i.e., when it consumes block space) or when it's spent (like for other normal script templates)?

**Comment by 0xB10C** [comment]
Thank you @harding for questioning the "Compression of spend PubKeys" chart! The title and the description are in fact misleading and incorrect. I forgot to update that after I updated the calculation... 

Currently, the chart represents a ratio of pubkeys (denominator is `compressed pubkeys + uncompressed pubkeys`). This includes both pubkeys present in inputs (in e.g. `P2PKH`, `P2WPKH`, and even multisig `P2WSH`) and outputs (in `P2PK`, `P2MS`). 

Thinking about it: It does make sense to split that up by inputs and outputs.

**Comment by 0xB10C** [comment]
Changed the [Public Key Compression](https://transactionfee.info/charts/bitcoin-script-pubkey-compression/) chart to show compression for inputs and outputs separately.

![Public Key Compression](https://user-images.githubusercontent.com/19157360/77256049-130b5900-6c6c-11ea-9143-c253effead49.png)
![image](https://user-images.githubusercontent.com/19157360/77256071-30402780-6c6c-11ea-8efd-52cd18d8854a.png)

**Comment by harding** [comment]
@0xB10C nice!  Thank you!
